from .views_academics import (
    ClassAddView,
    ClassDeleteView,
    ClassEditView,
    ClassListView,
    CourseAddView,
    CourseDeleteView,
    CourseEditView,
    CourseListView,
    CourseStudentsView,
    DepartAddView,
    DepartDeleteView,
    DepartEditView,
    DepartListView,
    SelectCourseView,
    StudentCourseView,
    UpdateGradeView,
)
from .views_auth import UserLoginView, UserLogoutView, UserPasswordView, UserRegisterView
from .views_misc import (
    AICodeExecutor,
    AuditLogListView,
    CODE_GENERATION_PROMPT,
    CodeValidator,
    DashboardView,
    SecurityError,
    chat_view,
    extract_code_from_response,
    format_execution_result,
    get_ai_response,
    make_json_safe,
)
from .views_students import (
    StudentAddView,
    StudentDeleteView,
    StudentDetailView,
    StudentEditView,
    StudentExportExcelView,
    StudentImportExcelView,
    StudentListView,
)
from .views_users import UserCreateView, UserEditView, UserListView

__all__ = [
    'UserLoginView',
    'UserLogoutView',
    'UserRegisterView',
    'UserPasswordView',
    'UserListView',
    'UserCreateView',
    'UserEditView',
    'StudentListView',
    'StudentAddView',
    'StudentImportExcelView',
    'StudentExportExcelView',
    'StudentDetailView',
    'StudentEditView',
    'StudentDeleteView',
    'ClassListView',
    'ClassAddView',
    'ClassEditView',
    'ClassDeleteView',
    'DepartListView',
    'DepartAddView',
    'DepartEditView',
    'DepartDeleteView',
    'CourseListView',
    'CourseAddView',
    'CourseEditView',
    'CourseDeleteView',
    'CourseStudentsView',
    'SelectCourseView',
    'StudentCourseView',
    'UpdateGradeView',
    'DashboardView',
    'AuditLogListView',
    'SecurityError',
    'CodeValidator',
    'AICodeExecutor',
    'CODE_GENERATION_PROMPT',
    'get_ai_response',
    'extract_code_from_response',
    'format_execution_result',
    'make_json_safe',
    'chat_view',
]

