# Generated by Django 5.2.9 on 2026-03-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cno', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('lecture', models.FloatField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('credit', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('crc', '公共课'), ('bcim', '专业基础课'), ('spc', '专业课'), ('ocos', '选修课')], default='crc', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='depart',
            fields=[
                ('dno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='cl',
            fields=[
                ('classno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=10)),
                ('dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xx.depart')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='girl', max_length=4)),
                ('native', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('entime', models.DateTimeField(auto_now=True, null=True)),
                ('semester', models.IntegerField(null=True)),
                ('home', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=20)),
                ('classno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xx.cl')),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(null=True)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xx.course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xx.student')),
            ],
        ),
    ]
