# Generated by Django 5.2.9 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='home',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='native',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
