# Generated by Django 5.2.9 on 2026-03-05 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_student_user_and_dedupe_sc(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Student = apps.get_model('xx', 'student')
    SC = apps.get_model('xx', 'sc')

    for stu in Student.objects.filter(user__isnull=True).iterator():
        user = User.objects.filter(username=stu.sno).first()
        if user:
            stu.user_id = user.id
            stu.save(update_fields=['user'])

    seen = set()
    duplicate_ids = []
    for row in SC.objects.order_by('id').values('id', 'sno_id', 'cno_id'):
        key = (row['sno_id'], row['cno_id'])
        if key in seen:
            duplicate_ids.append(row['id'])
        else:
            seen.add(key)

    if duplicate_ids:
        SC.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0003_alter_depart_telephone_alter_student_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='entime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(backfill_student_user_and_dedupe_sc, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sc',
            constraint=models.UniqueConstraint(fields=('sno', 'cno'), name='uniq_student_course'),
        ),
    ]
