# Generated by Django 5.2.9 on 2026-03-06 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


MANAGED_ROLES = ('admin', 'teacher', 'student')


def backfill_account_state_and_selection_status(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserAccount = apps.get_model('xx', 'UserAccount')
    StudentCourse = apps.get_model('xx', 'sc')

    for user in User.objects.all().iterator():
        roles = list(user.groups.filter(name__in=MANAGED_ROLES).values_list('name', flat=True))
        status = 'active' if roles else 'pending'
        UserAccount.objects.get_or_create(
            user=user,
            defaults={
                'status': status,
                'reviewed_at': django.utils.timezone.now() if roles else None,
            },
        )
        if status == 'disabled':
            user.is_active = False
        else:
            user.is_active = True
        user.save(update_fields=['is_active'])

    for record in StudentCourse.objects.all().iterator():
        record.selection_status = 'active'
        record.grade_status = 'published' if record.grade is not None else 'pending'
        record.save(update_fields=['selection_status', 'grade_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0005_backfill_student_login_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('selected', '选课'), ('dropped', '退课'), ('grade_saved', '保存成绩'), ('grade_published', '发布成绩'), ('retake_marked', '标记重修')], max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('before_selection_status', models.CharField(blank=True, max_length=20)),
                ('after_selection_status', models.CharField(blank=True, max_length=20)),
                ('before_grade_status', models.CharField(blank=True, max_length=20)),
                ('after_grade_status', models.CharField(blank=True, max_length=20)),
                ('before_grade', models.FloatField(blank=True, null=True)),
                ('after_grade', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('create', '新增模式'), ('update', '更新模式')], max_length=20)),
                ('status', models.CharField(choices=[('previewed', '已预检'), ('applied', '已导入')], default='previewed', max_length=20)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('error_rows', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '启用'), ('disabled', '停用')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cl',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='depart',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='attempt_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sc',
            name='dropped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='grade_status',
            field=models.CharField(choices=[('pending', '待录入'), ('draft', '草稿'), ('published', '已发布'), ('retake', '重修中')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sc',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='selected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sc',
            name='selection_status',
            field=models.CharField(choices=[('active', '已选'), ('dropped', '已退课')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='sc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cl',
            name='dno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xx.depart'),
        ),
        migrations.AlterField(
            model_name='sc',
            name='cno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xx.course'),
        ),
        migrations.AlterField(
            model_name='sc',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sc',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xx.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xx.cl'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sc',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 0), ('grade__lte', 100)), _connector='OR'), name='sc_grade_between_0_100'),
        ),
        migrations.AddField(
            model_name='selectionhistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionhistory',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='xx.sc'),
        ),
        migrations.AddField(
            model_name='studentimportjob',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='xx.cl'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='course_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='xx.course'),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'class_obj'), name='uniq_teacher_class_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teachercourseassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'course_obj'), name='uniq_teacher_course_assignment'),
        ),
        migrations.RunPython(backfill_account_state_and_selection_status, migrations.RunPython.noop),
    ]

